name: Deploy astro-blog to GitHub Pages

on:
  push:
    branches: ["main"]   # 当 main 分支有更新时触发
  workflow_dispatch:     # 允许手动触发部署

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码（包含子模块）
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'

      # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. 使用 pnpm 安装依赖
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # 5. 构建项目（生成在 dist 目录下）
      - name: Build Project
        run: pnpm build

      # 6. 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 7. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
